defaults: &defaults
    docker:
        - image: cimg/openjdk:8.0.275

version: 2.1

orbs:
  maven: circleci/maven@1.0.3

jobs:
  run_checkstyle:
    <<: *defaults
    working_directory: /tmp/repos/cmo-messaging-java
    steps:
      - checkout
      - run:
          name: "Build project..."
          command: mvn clean install
      - run:
          name: "Run checkstyle plugin..."
          command: mvn checkstyle:checkstyle
      - run:
          name: "Validating checkstyle plugin report..."
          command: bash test/scripts/generate_checkstyle_report.sh /tmp/repos/cmo-messaging-java
      - store_artifacts:
          path: /tmp/repos/cmo-messaging-java/checkstyle_report_compiled.txt
          destination: /checkstyle_report.txt

workflows:
  run_mvn_checkstyle:
    jobs:
        - run_checkstyle

